[devkit]
template = "1.1.0"
project  = "ITSC"
python   = "3.14"
apt      = ["rustup", "gcc"]
domains  = ["releases.hashicorp.com", "registry.terraform.io", "data.binance.vision", "static.rust-lang.org", "index.crates.io", "static.crates.io", "crates.io"]
