"""Bindings PyO3 sobre dc_core: fan-out de N θ y carry-over."""

from collections.abc import Sequence
from typing import Self

SCALE: int
PRICE_LIMIT: int
STATE_VERSION: str

# (price, time, agg_trade_id): precio entero en escala SCALE, tiempo en µs UTC.
type Point = tuple[int, int, int]

class Event:
    @property
    def direction(self) -> int: ...
    @property
    def reference(self) -> Point: ...
    @property
    def confirm(self) -> Point: ...
    @property
    def extreme(self) -> Point: ...

class CarryOver:
    def __new__(
        cls,
        theta: int,
        state_version: str,
        direction: int,
        ext_high: Point,
        ext_low: Point,
        pending: tuple[Point, Point] | None = None,
    ) -> Self: ...
    @property
    def theta(self) -> int: ...
    @property
    def state_version(self) -> str: ...
    @property
    def direction(self) -> int: ...
    @property
    def ext_high(self) -> Point: ...
    @property
    def ext_low(self) -> Point: ...
    @property
    def pending(self) -> tuple[Point, Point] | None: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> CarryOver: ...

class FanOut:
    def __new__(cls, thetas: Sequence[int], threads: int | None = None) -> Self: ...
    @staticmethod
    def from_carry_over(
        thetas: Sequence[int],
        carry: Sequence[CarryOver],
        threads: int | None = None,
    ) -> FanOut: ...
    @property
    def thetas(self) -> list[int]: ...
    def feed_batch(
        self,
        prices: memoryview,
        times: memoryview,
        ids: memoryview,
    ) -> list[list[Event]]: ...
    def finish(self) -> list[Event | None]: ...
    def discarded(self) -> list[int]: ...
    def carry_overs(self) -> list[CarryOver]: ...
    def __len__(self) -> int: ...
